# RNG Configuration

files:
  - grammars/basicdoc-compile.rnc
  - grammars/biblio-presentation.rnc
  - grammars/bipm.rnc
  - grammars/bsi.rnc
  - grammars/cc.rnc
  - grammars/gbstandard.rnc
  - grammars/generic.rnc
  - grammars/iec.rnc
  - grammars/ieee.rnc
  - grammars/ietf.rnc
  - grammars/iho.rnc
  - grammars/isodoc-collection.rnc
  - grammars/isodoc-compile.rnc
  - grammars/isodoc-presentation-compile.rnc
  - grammars/isostandard-amd.rnc
  - grammars/isostandard-compile.rnc
  - grammars/itu.rnc
  - grammars/jis.rnc
  - grammars/m3d.rnc
  - grammars/reqt.rnc
  - grammars/nist.rnc
  - grammars/ogc.rnc
  - grammars/plateau.rnc
  - grammars/relaton-3gpp-compile.rnc
  - grammars/relaton-bipm-compile.rnc
  - grammars/relaton-bsi-compile.rnc
  - grammars/relaton-cc-compile.rnc
  - grammars/relaton-ccsds-compile.rnc
  - grammars/relaton-cen-compile.rnc
  - grammars/relaton-cie-compile.rnc
  - grammars/relaton-csa-compile.rnc
  - grammars/relaton-ecma-compile.rnc
  - grammars/relaton-etsi-compile.rnc
  - grammars/relaton-gb-compile.rnc
  - grammars/relaton-iana-compile.rnc
  - grammars/relaton-iec-compile.rnc
  - grammars/relaton-ieee-compile.rnc
  - grammars/relaton-ietf-compile.rnc
  - grammars/relaton-iho-compile.rnc
  - grammars/relaton-iso-compile.rnc
  - grammars/relaton-itu-compile.rnc
  - grammars/relaton-jis-compile.rnc
  - grammars/relaton-m3aawg-compile.rnc
  - grammars/biblio-compile.rnc
  - grammars/biblio-standoc.rnc
  - grammars/biblio.rnc
  - grammars/relaton-mpfa-compile.rnc
  - grammars/relaton-nist-compile.rnc
  - grammars/relaton-oasis-compile.rnc
  - grammars/relaton-ogc-compile.rnc
  - grammars/relaton-omg-compile.rnc
  - grammars/relaton-plateau-compile.rnc
  - grammars/relaton-ribose-compile.rnc
  - grammars/relaton-un-compile.rnc
  - grammars/relaton-w3c-compile.rnc
  - grammars/ribose.rnc
  - grammars/un.rnc