cp basicdoc.rng ../../metanorma-standoc/lib/asciidoctor/standoc
cp reqt.rng ../../metanorma-standoc/lib/asciidoctor/standoc
cp biblio.rng ../../metanorma-standoc/lib/asciidoctor/standoc
cat isodoc.rng | ruby -pe '$_.gsub!(/<grammar /, %{<grammar ns="http://riboseinc.com/isoxml" }) '> ../../metanorma-standoc/lib/asciidoctor/standoc/isodoc.rng
cp basicdoc.rng ../../metanorma-iso/lib/asciidoctor/iso
cp reqt.rng ../../metanorma-iso/lib/asciidoctor/iso
cp biblio.rng ../../metanorma-iso/lib/asciidoctor/iso
cp isodoc.rng ../../metanorma-iso/lib/asciidoctor/iso
cp isostandard.rng ../../metanorma-iso/lib/asciidoctor/iso
cp basicdoc.rng ../../metanorma-iec/lib/asciidoctor/iec
cp reqt.rng ../../metanorma-iec/lib/asciidoctor/iec
cp biblio.rng ../../metanorma-iec/lib/asciidoctor/iec
cp isodoc.rng ../../metanorma-iec/lib/asciidoctor/iec
cat isostandard.rng | ruby -pe '$_.gsub!(/<grammar ns=\S+/, "<grammar") ' >  ../../metanorma-iec/lib/asciidoctor/iec/isostandard.rng
cp iec.rng ../../metanorma-iec/lib/asciidoctor/iec
cp basicdoc.rng ../../metanorma-gb/lib/asciidoctor/gb
cp reqt.rng ../../metanorma-gb/lib/asciidoctor/gb
cp biblio.rng ../../metanorma-gb/lib/asciidoctor/gb
cp isodoc.rng ../../metanorma-gb/lib/asciidoctor/gb
cat isostandard.rng | ruby -pe '$_.gsub!(/<grammar ns=\S+/, "<grammar") ' >  ../../metanorma-gb/lib/asciidoctor/gb/isostandard.rng
cp gbstandard.rng ../../metanorma-gb/lib/asciidoctor/gb
cp basicdoc.rng ../../metanorma-csd/lib/asciidoctor/csd
cp reqt.rng ../../metanorma-csd/lib/asciidoctor/csd
cp biblio.rng ../../metanorma-csd/lib/asciidoctor/csd
cp isodoc.rng ../../metanorma-csd/lib/asciidoctor/csd
cp csd.rng ../../metanorma-csd/lib/asciidoctor/csd
cp basicdoc.rng ../../metanorma-csand/lib/asciidoctor/csa
cp reqt.rng ../../metanorma-csand/lib/asciidoctor/csa
cp biblio.rng ../../metanorma-csand/lib/asciidoctor/csa
cp isodoc.rng ../../metanorma-csand/lib/asciidoctor/csa
cp csand.rng ../../metanorma-csand/lib/asciidoctor/csa
cp basicdoc.rng ../../metanorma-m3d/lib/asciidoctor/m3d
cp reqt.rng ../../metanorma-m3d/lib/asciidoctor/m3d
cp biblio.rng ../../metanorma-m3d/lib/asciidoctor/m3d
cp isodoc.rng ../../metanorma-m3d/lib/asciidoctor/m3d
cp m3d.rng ../../metanorma-m3d/lib/asciidoctor/m3d
cp basicdoc.rng ../../metanorma-rsd/lib/asciidoctor/rsd
cp reqt.rng ../../metanorma-rsd/lib/asciidoctor/rsd
cp biblio.rng ../../metanorma-rsd/lib/asciidoctor/rsd
cp isodoc.rng ../../metanorma-rsd/lib/asciidoctor/rsd
cp rsd.rng ../../metanorma-rsd/lib/asciidoctor/rsd
cp basicdoc.rng ../../metanorma-sample/lib/asciidoctor/sample
cp reqt.rng ../../metanorma-sample/lib/asciidoctor/sample
cp biblio.rng ../../metanorma-sample/lib/asciidoctor/sample
cp isodoc.rng ../../metanorma-sample/lib/asciidoctor/sample
cat rsd.rng | ruby -pe '$_.gsub!(/rsd-standard/, "sample-standard") ' > ../../metanorma-sample/lib/asciidoctor/sample/sample.rng
cp basicdoc.rng ../../metanorma-acme/lib/asciidoctor/acme
cp reqt.rng ../../metanorma-acme/lib/asciidoctor/acme
cp biblio.rng ../../metanorma-acme/lib/asciidoctor/acme
cp isodoc.rng ../../metanorma-acme/lib/asciidoctor/acme
cat rsd.rng | ruby -pe '$_.gsub!(/rsd-standard/, "acme-standard") ' > ../../metanorma-acme/lib/asciidoctor/acme/acme.rng
cp basicdoc.rng ../../metanorma-mpfd/lib/asciidoctor/mpfd
cp reqt.rng ../../metanorma-mpfd/lib/asciidoctor/mpfd
cp biblio.rng ../../metanorma-mpfd/lib/asciidoctor/mpfd
cp isodoc.rng ../../metanorma-mpfd/lib/asciidoctor/mpfd
cp mpfd.rng ../../metanorma-mpfd/lib/asciidoctor/mpfd
cp basicdoc.rng ../../metanorma-unece/lib/asciidoctor/unece
cp reqt.rng ../../metanorma-unece/lib/asciidoctor/unece
cp biblio.rng ../../metanorma-unece/lib/asciidoctor/unece
cp isodoc.rng ../../metanorma-unece/lib/asciidoctor/unece
cp unece.rng ../../metanorma-unece/lib/asciidoctor/unece
cp basicdoc.rng ../../metanorma-ogc/lib/asciidoctor/ogc
cp reqt.rng ../../metanorma-ogc/lib/asciidoctor/ogc
cp biblio.rng ../../metanorma-ogc/lib/asciidoctor/ogc
cp isodoc.rng ../../metanorma-ogc/lib/asciidoctor/ogc
cp ogc.rng ../../metanorma-ogc/lib/asciidoctor/ogc
cp basicdoc.rng ../../metanorma-nist/lib/asciidoctor/nist
cp reqt.rng ../../metanorma-nist/lib/asciidoctor/nist
cp biblio.rng ../../metanorma-nist/lib/asciidoctor/nist
cp isodoc.rng ../../metanorma-nist/lib/asciidoctor/nist
cp nist.rng ../../metanorma-nist/lib/asciidoctor/nist
cp basicdoc.rng ../../metanorma-ietf/lib/asciidoctor/ietf
cp reqt.rng ../../metanorma-ietf/lib/asciidoctor/ietf
cp biblio.rng ../../metanorma-ietf/lib/asciidoctor/ietf
cp isodoc.rng ../../metanorma-ietf/lib/asciidoctor/ietf
cp ietf.rng ../../metanorma-ietf/lib/asciidoctor/ietf
cp basicdoc.rng ../../metanorma-itu/lib/asciidoctor/itu
cp reqt.rng ../../metanorma-itu/lib/asciidoctor/itu
cp biblio.rng ../../metanorma-itu/lib/asciidoctor/itu
cp isodoc.rng ../../metanorma-itu/lib/asciidoctor/itu
cp itu.rng ../../metanorma-itu/lib/asciidoctor/itu
cp basicdoc.rng ../../metanorma-vsd/lib/asciidoctor/vsd
cp reqt.rng ../../metanorma-vsd/lib/asciidoctor/vsd
cp biblio.rng ../../metanorma-vsd/lib/asciidoctor/vsd
cp isodoc.rng ../../metanorma-vsd/lib/asciidoctor/vsd
cp rsd.rng ../../metanorma-vsd/lib/asciidoctor/vsd/vsd.rng
