== Introduction

Metanorma provides a document structure for standardization documents, specified in link:https://www.isotc154.org/projects/iso-36001/[ISO 36001]. Since each organization has different requirements for their standard documents, they use a “flavor” of Metanorma. A flavor is a document model that provides additional metadata to reflect the SDO’s needs. Metanorma currently supports 16 different "flavours", each corresponding to a different Stadnards-Defining Organisation.

To use the defined document metamodels, there needs to be a machine-readable file so that documents can be checked against their intended structure. These are defined as XML schemas.

This documentation describes the suite of XML schemas that define the structure of documents in Metanorma. It is primarily intended for consumers of Metanorma Presentation XML, who will generate renderings of Metanorma documents based on it.

[.preface]
== Document conventions

In listings of element content, attributes are prefixed with `@`. Types are capitalised, e.g. `FullNameType`. Elements are lowercase, e.g. `name`.

[.preface]
== Currency

The Metanorma schemas are updated relatively rapidly as new requirements emerge from the SDOs that Metanorma supports. Updates to the Metanorma schemas are published to https://github.com/metanorma/metanorma-model-iso/releases[the Metanorma schema release log], which should be read in conjunction with this document.
