[[document]]
== Document

=== `metanorma`

==== Semantic XML

===== StanDoc

A standardisation document contains at least the following data elements:

* Metadata information;
* Clauses and subclauses;
* Annexes if applicable;
* Bibliographies.

The document-level arrangement of content is specific to StanDoc, and not inherited from BasicDoc.

The specific content of a Metanorma document is:


`@schema-version`:: Version number of the schema used for this standards document. Corresponds to the release version
for the schema in https://github.com/metanorma/metanorma-model-iso/releases[the Metanorma schemas repository]
`@version`:: Version number of the gem used to generate this standards document in a specific flavour; so if this
is an ISO document generated by metanorma-iso version 3.0.3, the `version` attribute is `3.0.3`.
`@type`:: Whether this is a Semantic XML (`semantic`) or Presentation XML (`presentation`) document.
`@flavor`:: The flavour of Metanorma this document belongs to, corresponding to a particular Standards-Defining Organisation.
`bibdata` (<<bibdata>>):: Bibliographic description of the document itself, expressed as an extension of the Relaton
model.
`termdocsource`:: Source for term definitions in the document
`metanorma-extension`:: Extension point for extraneous elements that need to be added to standards document
from other schemas and data sources.
`boilerplate`:: An optional _boilerplate_ section, intended to appear at the
front of the document, with content not specific to the document. It consists of content addressing
_copyright_, _license_, _legal_, and _feedback_ concerns.
`preface`:: Zero or more optional _preface_ sections.
`sections`:: One or more main _section_ clauses.
`annex`:: Zero or more _annexes_.
`bibliography`:: Zero or more _bibliographies_.
`indexsect`:: Index of a standards document.
`colophon`:: Zero or more optional sections that appear as a colophon or postface.
`review-container`:: Container of annotations to the document

===== Flavours: ISO

ISO amendments have their own schema (`isostandard-amd.rnc`), with a much reduced set of content: they have no annexes,
bibliographies, indexes, or colophons.

==== Presentation XML

===== StanDoc

Presentation XML moves copies the presentation form of footnote bodies to a footnote container at the end of the document.
`fmt-footnote-container` (<<fmt-footnote-container>>). This is done so that footnote bodies are rendered together as a block.

===== Flavours: BIPM

In BIPM, `fmt-footnote-container` does not appear at the end of the document. Instead, each clause and subclause
can have a `fmt-footnote-container` element, containing only the footnote bodies specific to that clause.

