[[metadata]]
== Metadata

[[bibdata]]
=== `bibdata`

==== Relaton

`bibdata` is the container for document metadata.
Almost all the  elements within `bibdata` in Semantic XML are already defined in the Relaton citation model -- although `bibdata`
itself is not: these elements in Relaton are part of `bibitem`, the description of a bibliographic reference for citation.
Detailed documentation of the Relaton model is available in https://relaton.org[Relaton].

`@type`:: The type of the bibliographic item. This is always `standard` for standardisation documents.
`@schema-version`:: The version of the Relaton schema that this description conforms to. This is not populated for `bibdata`.
`fetched`:: The date at which the bibliographic item was last updated
`formattedref`:: A pre-formatted version of the full bibliographic item reference, rendered for human reading, and used to sidestep the rendering of the reference out of its component parts
`title`:: The title(s) of the bibliographic item
`source`:: The URI(s) associated with the bibliographic item
`docidentifier`:: The identifier(s) of the bibliographic item in an international standard scheme
`docnumber`:: Unprefixed, preferably numeric version of an identifier of the bibliographic item, intended for sorting of bibliography
`date`:: One or more date-times associated with the production of or access to the bibliographic item
`contributor`:: Contributors to the production of the bibliographic item (<<contributor>>)
`edition`:: The edition of the bibliographic item (<<edition>>)
`version`:: The version of the bibliographic item (within an edition). Can be used for drafts. Can be more than one, in case of multiple versioning schemes
`biblionote`:: Note(s) associated with the bibliographic item
`language`:: The language(s) in which the bibliographic item is expressed
`locale`:: The locale(s) in which the bibliographic item is expressed
`script`:: The script(s) in which the bibliographic item is written
`abstract`:: The abstract of the bibliographic item
`status`:: The publication or preparation status of the bibliographic item (<<status>>)
`copyright`:: The copyright status of the bibliographic item
`docrelation`:: The relation(s) of the bibliographic item to other bibliographic items
`series`:: The series of the bibliographic item
`medium`:: The medium the subject is realized on. Medium can be used to differentiate between "electronic" and "physical" manifestations of an information resource.
`place`:: The geographic location associated with the production of the bibliographic item
`price`:: The price set on accessing the bibliographic item. The price should be treated as nominal, rather than capturing all possible pricings at a given time
`extent`:: The extent of the bibliographic item, if reference is not being made to the entirety of the item described. Repeats for different levels of granularity (e.g. volume number, page number), or for discontinuous ranges (e.g. multiple page ranges, pages plus plates)
`size`:: The bibliographic size of the bibliographic item, measured in the same units as extent (i.e. pages, volumes, megabytes, hours, rather than cm^2^.) Distinct from the physical size of the bibliographic item, captured in medium/size
`accesslocation`:: The location where the bibliographic item may be accessed. Used for archival resources. Also used for pathways to access digital resources, where a URI is not practical
`license`:: A license under which the bibliographic item has been issued. NOTE: This should preferably be encoded as  a URI or short identifier, rather than descriptive text
`classification`:: The classification of the bibliographic item according to a standard classification scheme
`keyword`:: Keyword(s) for the bibliographic item
`validity`:: Information about how long the current description of the bibliographic item is valid for
`depiction`:: Depiction of the bibliographic item, typically an image

==== Semantic XML

The `biblio-standoc` schema introduces the `bibdata` element itself, used to describe standardisation document metadata.

The following elements are appended to `bibdata`:

`amend`:: Description of changes specific to this document (<<amend>>). This element is shared with `bibitem` under StanDoc
`ext`:: The extension point of the bibliographic description of a standardisation document (<<ext>>)

==== Presentation XML

In Presentation XML (`biblio-presentation.rnc`), internationalisation is introduced for metadata elements. 
That applies to `edition`, `status/stage`,
`status/substage`, `date`, and `ext/doctype`; it also changes their cardinality from 0..1 and 1 to 0..* and 1..*. In all of these cases,
the original Semantic XML value, without internationalisation, is indicated with `@language` = "". The internationalised
value introduced in Presentation XML is given as another instance of the same element, with `@language` set to the current
document language.

[[ext]]
=== `ext`

==== Semantic XML

===== StanDoc

The following elements appear in `ext` as recurring metadata elements for documents that are not part of the Relaton citiation model:

`@schema-version`:: The version of the flavour-specific schema that this extension point conforms to
`doctype`:: Classification of the standardisation document that is treated as a distinct series by the standards defining organization, and that is rendered in a distinct manner
`docsubtype`:: Subclass of the standardisation document, that is treated or processed differently from other documents in the same doctype
`flavor`:: Flavour of Metanorma used to process this document. Replicates `metanorma/@flavor`, used in order to retrieve flavour from
`bibdata` element explicitly, in contexts where metadata is processed separately (e.g. in collections).
`editorialgroup`:: Groups associated with the production of the standards document, typically within a standards definition organization
`ics`:: Classification of the document contents taken from the International Classification of Standards
`structuredidentifier`:: Representation of the identifier for the standardisation document, giving its individual semantic components

===== Flavours: ISO

The following elements are added for ISO document metadata:

`horizontal`:: Is this a horizontal standard document
`approvalgroup`:: Groups associated with the approval of the standards document, typically within a standards definition organization
`stagename`:: Human-readable name of the stage of publication, corresponding to the numeric stage code given in `/bibdata/status/stage`
`updates-document-type`:: if this is an update to another document (e.g. an amendment), the `doctype` will not indicate what type of 
document is being updated (e.g. that this is an amendment to a technical report, as opposed to an amendment to a technical standard).
The `updates-document-type` value indicates the document type of the document being updated; this may be needed for proper rendering, or
to formulate the document identifier properly
`fast-track`:: Whether this is a fast-tracked standard
`price-code`:: The price code of the standard

===== Flavours: IETF

The following elements are added for IETF document metadata:

`area`:: IETF area of coverage
`stream`:: IETF stream including the document
`ipr`:: IPR classification of document
`processing-instructions`:: processing instructions for RFC XML
`consensus`:: IETF consensus
`index-include`:: IETF directive to include index in generated document
`ipr-extract`:: IETF directive to extract IPR
`sort-refs`:: IETF directive to sort references
`sym-refs`:: IETF directive to use symbolic references
`toc-include`:: IETF directive to include table of contents
`toc-depth`:: IETF directive to specify depth of table of contents
`show-on-front-page`:: IETF directive to display material on the front page

===== Flavours: IEEE

The following elements are added for IEEE document metadata:

`trialuse`:: Trial use status of document
`standard_status`::  Status of standard (inactive, active, superseded)
`standard_modified`:: Modification status of standard (draft, withdrawn, superseded, approved, reserved, redline)
`pubstatus`:: Publication status of document (active, inactive)
`holdstatus`::  Hold status of document (hold, publish)
`program`:: Program that document belongs to

===== Flavours: ITU

The following elements are added for ITU document metadata:

`question`:: Question group under which document was authored
`recommendationstatus`:: Recommendation status of document
`ipnoticereceived`:: Whether an IP notice has been received for the document
`meeting`:: Meeting during which document is being considered
`meeting-place`:: Place of meeting during which document is being considered
`meeting-date`:: Date of meeting during which document is being considered
`intended-type`:: Intended type of document, if it is a proposal (R, C, TD)
`source`:: Source of document

===== Flavours: NIST

The following elements are added for NIST document metadata:

`commentperiod`:: Period during which document is open for comment

===== Flavours: IHO

The following elements are added for IHO document metadata:

`commentperiod`:: Period during which document is open for comment

===== Flavours: Ribose

The following elements are added for Ribose document metadata:

`security`:: Security attribute of document

===== Flavours: JIS

The following elements are added for JIS document metadata:

`stagename`:: Human-readable name of the stage of publication, corresponding to the numeric stage code given in `/bibdata/status/stage`

===== Flavours: IEC

The following elements are added for IEC document metadata:

`horizontal`:: Is this a horizontal standard document
`function`:: Function of document (emc, safety, environment, quality-assurance)
`stagename`:: Human-readable name of the stage of publication, corresponding to the numeric stage code given in `/bibdata/status/stage`
`updates-document-type`:: if this is an update to another document (e.g. an amendment), the `doctype` will not indicate what type of 
document is being updated (e.g. that this is an amendment to a technical report, as opposed to an amendment to a technical standard).
The `updates-document-type` value indicates the document type of the document being updated; this may be needed for proper rendering, or
to formulate the document identifier properly
`price-code`:: The price code of the standard
`accessibility-color-inside`: Whether accessibility colour information is given for the document
`cen-processing`::  Whether CEN processing is done on the document
`secretary`:: The secretariat responsible for the document
`interest-to-committees`:: Declaration of interest to committees
`tc-sc-officers-note`:: Note for technical committee and subcommittee officers

===== Flavours: BSI

The following elements are added for BSI document metadata:

`stagename`:: Human-readable name of the stage of publication, corresponding to the numeric stage code given in `/bibdata/status/stage`

===== Flavours: BIPM

The following elements are added for BIPM document metadata:

`comment-period`:: Period during which document is open for comment
`si-aspect`:: The SI aspect focussed on in the document
`meeting-note``:: Note for meeting considering the document

===== Flavours: Plateau

The following elements are added for Plateau document metadata:

`stagename`:: Human-readable name of the stage of publication, corresponding to the numeric stage code given in `/bibdata/status/stage`
`filesize`:: The size of the document file

==== Presentation XML

Alongside the Semantic XML `doctype` instance, add a `doctype` instance with `@current = true`, giving a translation of the doctype 
into the current internationalisation language.

[[status]]
=== `status`

==== Relaton

The publication or preparation status of a document.

`stage`:: The stage of the document status, e.g. "Published", "Unpublished", "Committee Draft", "Preprint" (<<stage>>)
`substage`:: The substage of the document status. These are used particularly in Standards Defining Organizations (<<substage>>)
`iteration`:: The iteration of the given status that the document is currently in (e.g. "3" for a third draft)

[[stage]]
=== `stage`

==== Relaton

The stage of the document status, e.g. "Published", "Unpublished", "Committee Draft", "Preprint"

`@abbreviation`:: A canonical abbreviation of the document stage
(value):: The name of the document stage

[[substage]]
=== `substage`

==== Relaton

The substage of the document status. These are used particularly in Standards Defining Organizations

`@abbreviation`:: A canonical abbreviation of the document substage
(value):: The name of the document substage

[[edition]]
=== `edition`

==== Relaton 

Edition of a bibliographic item

`@number`:: Number of edition. The number attribute can be used to represent the numeric equivalent of the edition string
(value):: Formatted, human-readable edition string

[[contributor]]
=== `contributor`

==== Relaton

Description of a contributor to the production of the bibliographic item

`role`:: A description of the role of the contributor in the production of the bibliographic item (<<role>>)
`person`: The contributor involved in the production of the bibliographic item, if a person (<<person>>)
`organization`: The contributor involved in the production of the bibliographic item, if an organisation

[[role]]
=== `role`

==== Relaton

A description of the role of the contributor in the production of a bibliographic item

`@type`:: The broad class of role of the contributor. Mandatory in order to enforce orderly management of contributors.
Detailed in https://www.relaton.org/model/creator/
`description`:: A more detailed description of the role of the contributor (<<LocalizedMarkedUpString>>)

[[person]]
=== `person`

=== Relaton

Person associated with a bibliographic item

`name`:: The name of the person (<<FullNameType>>)
`credential`:: Credentials given for the person postnominally, e.g. "PhD"
`affiliation`::  The affiliation of the person within an organization
`identifier`:: An identifier of the person according to an international identifier scheme
`Contact`:: Contact information for the person, including URI, address, phone number, and email

[[FullNameType]]
=== `FullNameType`
