@startuml IsoDoc_IsoStandardDocument
/'
Diagram:        IsoDoc_IsoStandardDocument
DateCreate:     22/08/2018
Description:    Metanorma IsoDoc is a family of document models intended to represent ISO Standards and similarly structured standards, 
                based on the Metanorma StandardDocument ("StanDoc") and BasicDocument ("BasicDoc") models.
                It is used to abstract the automated generation of standard documents in various formats from well-defined authoring tools; 
                and to validate the structural conformance of authored standards to specifications.
                The standards currently modelled via Metanorma IsoDoc are:
                
                - ISO Standards
                - CSD Standards
                - Chinese Standards (GB and family)
                
                The base Metanorma StandardDocument model includes information common to all standards in scope of IsoDoc. 
                Models for individual standards are derived from the base model as subclasses, permitting changes in cardinality of attributes, 
                and changes in their type.
                
                Models it depends on include:
                
                - Relaton Bibliography models: BibModels
                - BasicDoc models: BasicDoc
                - Metanorma StandDoc models: StanDoc
                
                Below, we show the UML diagrams for the base model and for ISO. The CSD, GB diagrams are shown on their own respective pages.
                The document models are expressed as UML and as RelaxNG Compact (RNC) grammars; see discussion under Grammars. 
                This repository contains the RNC grammars for the base Standard Document model, ISO Standards, CSD and China Standards.
                
                The document models are currently used by Asciidoctor-based authoring tools for standards, 
                which convert Asciidoctor source to XML representations of the document models, and validate the XML generated against the RNC schemas:
                
                - https://github.com/metanorma/metanorma-iso
                - https://github.com/metanorma/metanorma-csd
                - https://github.com/metanorma/metanorma-gb
                - And so on
                
                They are also used by tools that render those XML representations of the document models, into HTML and Microsoft Word:
                
                - https://github.com/metanorma/isodoc
                - https://github.com/metanorma/metanorma-csd (inheriting from isodoc)
                - https://github.com/metanorma/metanorma-gb (inheriting from isodoc)
                - And so on

Hystory of changes:
> DD/MM/YYYY
    - 
    - 
'/

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class StandardDocument <<StandardDocument>> {

}

class IsoStandardDocument {
    +bibdata: IsoBibliographicItem
    +prefix: IsoPreface
    +sections: ClauseSection[1..*]
    +annex: AnnexSection[0..*]
    +termSources: <<Bibliography>> Citation[0..*]
}

class IsoPreface{
    +foreword: BasicSection
    +introduction: ClauseSection[0..1]
}

class AnnexSection <<StandardDocument>>{

}

class IsoAnnexSection{
    +appendix: ClauseSection[0..*]
}

'******* NOTES ********************************************************
note "'termSource' points to\nother ISO Documents where\nthis document inherit their\nTerms and Definition /\nSymbols /\n Abbreviations" as N1

'******* CLASS RELATIONS **********************************************
StandardDocument <|-- IsoStandardDocument
IsoStandardDocument <-- IsoPreface

AnnexSection <|-- IsoAnnexSection

@enduml
